version: "2"

services:
  app:
    image: app
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-8.1.0}
    volumes:
      - ./:/var/www/app
      - /var/www/app/vendor
    extra_hosts:
      - "internal.host:host-gateway"
    links:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/app:cached
    restart: on-failure
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - laravel

#  ngrok:
#    image: ngrok/ngrok
#    links:
#      - app
#    command:
#      - "start"
#      - "--all"
#      - "--config"
#      - "/etc/ngrok.yml"
#    volumes:
#      - ./.docker/ngrok/ngrok.yml:/etc/ngrok.yml
#    ports:
#      - "4040:4040"
#    networks:
#      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8082:80"
    networks:
      - laravel

networks:
  laravel:
  #driver: bridge
